version: "3.9"

services:
  backend:
    build:
      context: ./detailing-be
      dockerfile: Dockerfile
    hostname: highenddetailing
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - spring.datasource.url=jdbc:mysql://192.168.2.139:3306/high_end_DB?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://backend:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./detailing-fe
      dockerfile: Dockerfile
      args:
        REACT_APP_AUTH0_DOMAIN: ${AUTH0_DOMAIN}
        REACT_APP_AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
        REACT_APP_AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
        REACT_APP_AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
        REACT_APP_AUTH0_CALLBACK_URL: "http://localhost:3000"
        REACT_APP_API_SERVER_URL: "http://localhost:3000"
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - ./detailing-fe:/app
      - /app/node_modules
      - /app/build
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  #  db:
  #    image: mysql:latest
  #    container_name: mysql-server
  #    restart: always
  #    ports:
  #      - "3306:3306"
  #    environment:
  #      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #      MYSQL_DATABASE: ${MYSQL_DATABASE}
  #      MYSQL_USER: ${MYSQL_USER}
  #      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #    volumes:
  #      - /mnt/cache/appdata/mysql/data:/var/lib/mysql
  #      - /mnt/cache/appdata/mysql/logs:/var/log/mysql
  #    healthcheck:
  #      test:
  #        [
  #          "CMD-SHELL",
  #          "mysqladmin ping -h localhost -uroot -p${MYSQL_ROOT_PASSWORD} || exit 1",
  #        ]
  #      interval: 30s
  #      timeout: 10s
  #      retries: 3

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin
    restart: always
    ports:
      - "5013:80"
    environment:
      PMA_HOST: 192.168.2.139
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
