services:
  backend:
    build:
      context: ./detailing-be
      dockerfile: Dockerfile
    hostname: highenddetailing
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on: []

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://backend:8080 || exit 1"] # Check if backend is accessible
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./detailing-fe
      dockerfile: Dockerfile
      args:
        REACT_APP_AUTH0_DOMAIN: ${AUTH0_DOMAIN}
        REACT_APP_AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
        REACT_APP_AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
        REACT_APP_AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
        REACT_APP_AUTH0_CALLBACK_URL: "http://localhost:3000"
        REACT_APP_API_SERVER_URL: "http://localhost:3000"
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 512M # Limit the container to 128 MB of RAM
    volumes:
      - ./detailing-fe:/app
      - /app/node_modules # Avoid overwriting node_modules
      - /app/build
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"] # Check if the frontend is accessible
      interval: 30s # Check every 30 seconds
      timeout: 10s # Timeout after 10 seconds
      retries: 3 # Mark as unhealthy after 3 failed checks

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin
    restart: always
    ports:
      - "5013:80"
    environment:
      PMA_USER: ${SPRING_DATASOURCE_USERNAME}
      PMA_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
