services:
  backend:
    build:
      context: ./detailing-be
      dockerfile: Dockerfile
    hostname: highenddetailing
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    depends_on:
      mysql1:
        condition: service_healthy

  frontend:
    build:
      context: ./detailing-fe
      dockerfile: Dockerfile
      args:
        REACT_APP_AUTH0_DOMAIN: ${AUTH0_DOMAIN}
        REACT_APP_AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
        REACT_APP_AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
        REACT_APP_AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
        REACT_APP_AUTH0_CALLBACK_URL: "http://localhost:3000"
        REACT_APP_API_SERVER_URL: "http://localhost:3000"
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 512M # Limit the container to 512 MB of RAM
    # Remove volume mounts for production
    # volumes:
    #   - ./detailing-fe:/workspace
    #   - /workspace/node_modules # Avoid overwriting node_modules
    #   - /workspace/build

  mysql1:
    image: mysql:8.0
    container_name: highenddetailing-mysql1
    environment:
      MYSQL_ROOT_PASSWORD: zaynabFA911
      MYSQL_DATABASE: highenddetailing-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: pwd
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql1:/var/lib/mysql1
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uadmin", "-ppwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin
    links:
      - mysql1
    restart: always
    ports:
      - "5013:80"
    environment:
      PMA_ARBITRARY: 1