services:
  backend:
    build:
      context: ./detailing-be
      dockerfile: Dockerfile
    hostname: highenddetailing
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      frontend:
        condition: service_started

  frontend:
    build:
      context: ./detailing-fe
      dockerfile: Dockerfile
      args:
        REACT_APP_AUTH0_DOMAIN: ${AUTH0_DOMAIN}
        REACT_APP_AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
        REACT_APP_AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
        REACT_APP_AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
        REACT_APP_AUTH0_CALLBACK_URL: "http://localhost:3000"
        REACT_APP_API_SERVER_URL: "http://localhost:3000"
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 512M # Limit the container to 512 MB of RAM
    volumes:
      - ./detailing-fe:/app
      - /app/node_modules # Avoid overwriting node_modules
      - /app/build