frontend:
  url: https://highend-zke6.onrender.com

backend:
  url: https://highend-1.onrender.com

website:
  domain: highend-zke6.onrender.com

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  config:
    activate:
      on-profile: docker

  sql:
    init:
      platform: mysql
      mode: always

auth0:
  domain: ${AUTH0_DOMAIN}
  clientId: ${AUTH0_CLIENT_ID}
  clientSecret: ${AUTH0_CLIENT_SECRET}
  audience: ${AUTH0_AUDIENCE}
  issuer: https://${AUTH0_DOMAIN}/

okta:
  oauth2:
    issuer: https://${AUTH0_DOMAIN}/
    audience: ${AUTH0_AUDIENCE}

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: admin
    password: pwd
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

  web:
    resources:
      static-locations: classpath:/custom/, classpath:/static/
