// import { test, expect } from '@playwright/test';

// test('test', async ({ page }) => {
//   await page.goto('http://localhost:3000/home');
//   await page.getByRole('button', { name: 'Register' }).click();
//   await page.getByPlaceholder('First Name').click();
//   await page.getByPlaceholder('First Name').fill('j');
//   await page.getByPlaceholder('Last Name').click();
//   await page.getByPlaceholder('Last Name').fill('j');
//   await page.getByPlaceholder('Email').click();
//   await page.getByPlaceholder('Email').fill('k');
//   await page.getByPlaceholder('Street Address').click();
//   await page.getByPlaceholder('Street Address').fill('1');
//   await page.getByPlaceholder('City').click();
//   await page.getByPlaceholder('City').fill('1');
//   await page.getByPlaceholder('Postal Code').click();
//   await page.getByPlaceholder('Postal Code').fill('1');
//   await page.getByPlaceholder('Province').click();
//   await page.getByPlaceholder('Province').fill('1');
//   await page.getByPlaceholder('Country').click();
//   await page.getByPlaceholder('Country').fill('1');
//   await page.getByRole('button', { name: 'Submit' }).click();
//   await page.getByRole('link', { name: 'Sign up' }).click();
//   await page.getByLabel('Email address').click();
//   await page.getByLabel('Email address').fill('g');
//   await page.getByLabel('Password').click();
//   await page.getByLabel('Password').press('CapsLock');
//   await page.getByRole('button', { name: 'Continue', exact: true }).click();
//   await page.getByRole('button', { name: 'Accept' }).click();
//   await page.getByRole('button', { name: 'Log Out' }).click();
//   await page.getByRole('button', { name: 'Login' }).click();
//   await page.getByLabel('Email address').click();
//   await page.getByLabel('Email address').fill('a');
//   await page.getByLabel('Password').click();
//   await page.getByLabel('Password').press('CapsLock');
//   await page.getByRole('button', { name: 'Continue', exact: true }).click();
//   await page.getByRole('link', { name: 'Dashboard' }).first().click();
//   await page.goto('http://localhost:3000/dashboard');
// });
