name: CI Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Make Gradlew Executable
        working-directory: ./detailing-be
        run: chmod +x gradlew
      - name: Run Gradle Tests
        working-directory: ./detailing-be
        run: ./gradlew clean test
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2023.1
        with:
          project-dir: ./detailing-be
          results-dir: ./qodana-results
          fail-threshold: 10
  prettier:
    name: Run Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        working-directory: ./detailing-fe
        run: npm install

      - name: Run Prettier Check
        working-directory: ./detailing-fe
        run: npx prettier --check .
