name: Frontend ESLint CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: detailing-fe/package-lock.json
      - name: Install dependencies
        run: npm install
        working-directory: ./detailing-fe
      - name: Run ESLint to ensure frontend code is linted
        run: npm run lint
        working-directory: ./detailing-fe
      - name: Run build to ensure no build errors
        run: npm run build
        working-directory: ./detailing-fe